apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplecalccluser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplecalccluser
  template:
    metadata:
      labels:
        app: simplecalccluser
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: simplecalccluser
        image: jtamimi/password-generator:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi


---
apiVersion: v1
kind: Service
metadata:
  name: simplecalccluser
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: simplecalccluser
