# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  docker:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker image
      run: docker build -t hajaraburmeileh/simplecalc:${{ github.sha }} -t hajaraburmeileh/simplecalc:latest .
    - name: Publish Docker image
      run: docker push hajaraburmeileh/simplecalc --all-tags

  azure:
    runs-on: ubuntu-latest
    needs: docker
    env:
      env-file: my-environment-file.env
      CLUSTER_NAME: simplecalccluser
      RESOURSE_GROUP: hajarscalc    
    
    steps:

      - uses: actions/checkout@v3
      - uses: azure/login@v1
        name: Azure login
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - uses: azure/use-kubelogin@v1
        name: Set up kubelogin for non-interactive login
        with:
          kubelogin-version: v0.0.25
      - uses: azure/aks-set-context@v3
        name: Get K8s context
        with:
          admin: "false"
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.RESOURSE_GROUP }}
          use-kubelogin: "true"
          
      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            kubernetes/deploy.yml
          images: |
            hajaraburmeileh/simplecalc:${{ github.sha }}
    
   

